server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/e3122?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 599964122345-a8pka48aifevl2kvcm1mkn59an9t3076.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          # 네이버는 spring security가 기본적을 제공해주지 않기 때문에 github, google과 달리 많은 정보를 적어줘야한다.
          kakao:
            client-id: 781439d4c65490bbf7fa59a3bee09329
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization_grant_type: authorization_code
            scope: profile_nickname,account_email,profile_image
            client-name: Kakao
            client-authentication-method: POST
          naver:
            client-id: bG0qcPV0iE8UxyHnjNlI
            client-secret: FMvhsaLZeE
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false
